"""Add Workflow model

Revision ID: 3b8b7cf5a116
Revises: d7345b3cee21
Create Date: 2024-11-16 22:09:58.186423

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3b8b7cf5a116'
down_revision = 'd7345b3cee21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflow',
    sa.Column('type', sa.Enum('build_dataset', name='workflowtype'), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('state', sa.Enum('SCHEDULED', 'PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', 'CRASHED', 'PAUSED', 'CANCELLING', name='statetype'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('related_dataset_id', sa.Integer(), nullable=False),
    sa.Column('prefect_flow_run_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('is_remote', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['related_dataset_id'], ['dataset.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('graphdisplayspecifications', 'node_label_field_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('graphdisplayspecifications', 'node_colors')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('graphdisplayspecifications', sa.Column('node_colors', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.alter_column('graphdisplayspecifications', 'node_label_field_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_table('workflow')
    # ### end Alembic commands ###
