"""add timestamps to Workflow

Revision ID: 7d2d7b886f47
Revises: 0db88d1f8303
Create Date: 2024-12-12 11:53:30.333991

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '7d2d7b886f47'
down_revision = '0db88d1f8303'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflow', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('workflow', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('workflow', sa.Column('started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('workflow', sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflow', 'ended_at')
    op.drop_column('workflow', 'started_at')
    op.drop_column('workflow', 'updated_at')
    op.drop_column('workflow', 'created_at')
    # ### end Alembic commands ###
