"""Add GraphDisplaySpecifications to Dataset

Revision ID: ae629a6b4c5b
Revises: 8afe3ce571b0
Create Date: 2024-10-23 09:55:10.743822

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'ae629a6b4c5b'
down_revision = '8afe3ce571b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('graphdisplayspecifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('node_label_field_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('dataset', sa.Column('graph_display_specifications_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'dataset', 'graphdisplayspecifications', ['graph_display_specifications_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'dataset', type_='foreignkey')
    op.drop_column('dataset', 'graph_display_specifications_id')
    op.drop_table('graphdisplayspecifications')
    # ### end Alembic commands ###
