"""Add node_colors and node_icons to GraphDisplaySpecifications

Revision ID: d7345b3cee21
Revises: ae629a6b4c5b
Create Date: 2024-10-23 15:09:08.331067

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'd7345b3cee21'
down_revision = 'ae629a6b4c5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('graphdisplayspecifications', sa.Column('node_colors', sa.JSON(), nullable=True))
    op.add_column('graphdisplayspecifications', sa.Column('node_icons', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('graphdisplayspecifications', 'node_icons')
    op.drop_column('graphdisplayspecifications', 'node_colors')
    # ### end Alembic commands ###
