/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ResetPasswordImport } from './routes/reset-password'
import { Route as RecoverPasswordImport } from './routes/recover-password'
import { Route as LoginImport } from './routes/login'
import { Route as LayoutImport } from './routes/_layout'
import { Route as LayoutIndexImport } from './routes/_layout/index'
import { Route as LayoutSettingsImport } from './routes/_layout/settings'
import { Route as LayoutItemsImport } from './routes/_layout/items'
import { Route as LayoutGraphcytoscapeImport } from './routes/_layout/graph_cytoscape'
import { Route as LayoutAdminImport } from './routes/_layout/admin'
import { Route as LayoutWorkflowsIndexImport } from './routes/_layout/workflows/index'
import { Route as LayoutDatasetsIndexImport } from './routes/_layout/datasets/index'
import { Route as LayoutWorkflowsIdImport } from './routes/_layout/workflows/$id'
import { Route as LayoutDatasetsIdImport } from './routes/_layout/datasets/$id'

// Create/Update Routes

const ResetPasswordRoute = ResetPasswordImport.update({
  path: '/reset-password',
  getParentRoute: () => rootRoute,
} as any)

const RecoverPasswordRoute = RecoverPasswordImport.update({
  path: '/recover-password',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const LayoutIndexRoute = LayoutIndexImport.update({
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutSettingsRoute = LayoutSettingsImport.update({
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutItemsRoute = LayoutItemsImport.update({
  path: '/items',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutGraphcytoscapeRoute = LayoutGraphcytoscapeImport.update({
  path: '/graph_cytoscape',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutAdminRoute = LayoutAdminImport.update({
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutWorkflowsIndexRoute = LayoutWorkflowsIndexImport.update({
  path: '/workflows/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutDatasetsIndexRoute = LayoutDatasetsIndexImport.update({
  path: '/datasets/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutWorkflowsIdRoute = LayoutWorkflowsIdImport.update({
  path: '/workflows/$id',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutDatasetsIdRoute = LayoutDatasetsIdImport.update({
  path: '/datasets/$id',
  getParentRoute: () => LayoutRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/recover-password': {
      preLoaderRoute: typeof RecoverPasswordImport
      parentRoute: typeof rootRoute
    }
    '/reset-password': {
      preLoaderRoute: typeof ResetPasswordImport
      parentRoute: typeof rootRoute
    }
    '/_layout/admin': {
      preLoaderRoute: typeof LayoutAdminImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/graph_cytoscape': {
      preLoaderRoute: typeof LayoutGraphcytoscapeImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/items': {
      preLoaderRoute: typeof LayoutItemsImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/settings': {
      preLoaderRoute: typeof LayoutSettingsImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/': {
      preLoaderRoute: typeof LayoutIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/datasets/$id': {
      preLoaderRoute: typeof LayoutDatasetsIdImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/workflows/$id': {
      preLoaderRoute: typeof LayoutWorkflowsIdImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/datasets/': {
      preLoaderRoute: typeof LayoutDatasetsIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/workflows/': {
      preLoaderRoute: typeof LayoutWorkflowsIndexImport
      parentRoute: typeof LayoutImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  LayoutRoute.addChildren([
    LayoutAdminRoute,
    LayoutGraphcytoscapeRoute,
    LayoutItemsRoute,
    LayoutSettingsRoute,
    LayoutIndexRoute,
    LayoutDatasetsIdRoute,
    LayoutWorkflowsIdRoute,
    LayoutDatasetsIndexRoute,
    LayoutWorkflowsIndexRoute,
  ]),
  LoginRoute,
  RecoverPasswordRoute,
  ResetPasswordRoute,
])

/* prettier-ignore-end */
